spring:
  application:
    name: configClient
  rabbitmq:
    host: 39.106.173.77
    port: 5672
    username: admin
    password: admin
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        register-health-check: true
name: xiaoli
